version: "3.9"

services:
  db:
    image: ankane/pgvector
    container_name: cgms_db
    restart: always
    environment:
      POSTGRES_DB: cgms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - cgms_data:/var/lib/postgresql/data

volumes:
  cgms_data: