from app.services.product_readiness.models import (
    Capability,
    CapabilityPriority,
    CapabilityStatus,
)


_STATUS_BY_SOURCE = {
    "Implemented": CapabilityStatus.IMPLEMENTED,
    "Partial": CapabilityStatus.IN_PROGRESS,
    "Partially Implemented": CapabilityStatus.IN_PROGRESS,
    "Foundation": CapabilityStatus.IN_PROGRESS,
    "Planned": CapabilityStatus.NOT_STARTED,
    "Future": CapabilityStatus.NOT_STARTED,
}


def _capability(
    capability_id: str,
    name: str,
    category: str,
    priority: CapabilityPriority,
    mlp: str,
    pilot: str,
    source_readiness: str,
    security_dependency: str,
    customer_value: str,
    commercial_importance: str,
    target: str,
    *,
    status_override: CapabilityStatus | None = None,
    security_reviewed: bool = False,
    ux_complete: bool = False,
    tests_passing: bool | None = None,
    documented: bool = False,
    evidence_note: str | None = None,
) -> Capability:
    """
    Build a capability from the approved product-prioritization matrix.

    Source readiness is translated conservatively into the Product
    Readiness Engine status model.
    """
    try:
        status = _STATUS_BY_SOURCE[source_readiness]
    except KeyError as exc:
        raise ValueError(
            f"Unsupported source readiness: {source_readiness}"
        ) from exc

    resolved_status = (
        status_override
        if status_override is not None
        else status
    )
    resolved_tests_passing = (
        tests_passing
        if tests_passing is not None
        else source_readiness == "Implemented"
    )
    notes = (
        f"Source readiness: {source_readiness}; "
        f"MLP classification: {mlp}; "
        f"Pilot classification: {pilot}; "
        f"Security dependency: {security_dependency}; "
        f"Customer value: {customer_value}; "
        f"Commercial importance: {commercial_importance}; "
        f"Target: {target}."
    )

    if evidence_note:
        notes += f" Evidence: {evidence_note}"

    return Capability(
        id=capability_id,
        name=name,
        category=category,
        priority=priority,
        status=resolved_status,
        required_for_mlp=mlp == "Yes",
        required_for_pilot=pilot == "Yes",
        security_reviewed=security_reviewed,
        ux_complete=ux_complete,
        tests_passing=resolved_tests_passing,
        documented=documented,
        notes=notes,
    )


PRODUCT_CAPABILITIES: tuple[Capability, ...] = (
    _capability(
        "CAP-001",
        "Secure Authentication",
        "Governance",
        CapabilityPriority.P0,
        "Yes",
        "Yes",
        "Partial",
        "Critical",
        "High",
        "Critical",
        "Pre-Pilot",
    ),
    _capability(
        "CAP-002",
        "Role-Based Access Control",
        "Governance",
        CapabilityPriority.P0,
        "Yes",
        "Yes",
        "Partial",
        "Critical",
        "High",
        "Critical",
        "Pre-Pilot",
    ),
    _capability(
        "CAP-003",
        "Workspace Isolation",
        "Governance / Memory",
        CapabilityPriority.P0,
        "Yes",
        "Yes",
        "Implemented",
        "Critical",
        "High",
        "Critical",
        "Pre-Pilot",
        status_override=CapabilityStatus.PILOT_READY,
        security_reviewed=True,
        ux_complete=True,
        tests_passing=True,
        documented=True,
        evidence_note=(
            "Steps 187F and 264K-264M validated persistent "
            "workspace isolation, workspace-bound authorization, "
            "control-plane persistence and cross-workspace denial "
            "on PostgreSQL 16 / pgvector."
        ),
    ),
    _capability(
        "CAP-004",
        "Persistent Audit Store",
        "Governance",
        CapabilityPriority.P0,
        "Yes",
        "Yes",
        "Implemented",
        "Critical",
        "High",
        "Critical",
        "Pre-Pilot",
        status_override=CapabilityStatus.PILOT_READY,
        security_reviewed=True,
        ux_complete=True,
        tests_passing=True,
        documented=True,
        evidence_note=(
            "Steps 264P-264S validated unified persistent enterprise "
            "audit across security, domain events, explainability and "
            "governance, including PostgreSQL 16 / pgvector migration, "
            "append-only enforcement, workspace-scoped reads, "
            "idempotence and complete regression."
        ),
    ),
    _capability(
        "CAP-005",
        "Backup and Restore",
        "Operations",
        CapabilityPriority.P0,
        "Yes",
        "Yes",
        "Planned",
        "High",
        "High",
        "Critical",
        "Pre-Pilot",
    ),
    _capability(
        "CAP-006",
        "Structured Organizational Memory",
        "Memory",
        CapabilityPriority.P1,
        "Yes",
        "Yes",
        "Implemented",
        "Medium",
        "Critical",
        "Critical",
        "MLP",
    ),
    _capability(
        "CAP-007",
        "Memory Lifecycle Actions",
        "Memory",
        CapabilityPriority.P1,
        "Yes",
        "Yes",
        "Implemented",
        "Medium",
        "High",
        "High",
        "MLP",
    ),
    _capability(
        "CAP-008",
        "Enterprise Memory Intelligence",
        "Intelligence",
        CapabilityPriority.P1,
        "Yes",
        "Yes",
        "Implemented",
        "Medium",
        "Critical",
        "Critical",
        "MLP",
    ),
    _capability(
        "CAP-009",
        "Explainability",
        "Intelligence / Governance",
        CapabilityPriority.P1,
        "Yes",
        "Yes",
        "Implemented",
        "Medium",
        "Critical",
        "Critical",
        "MLP",
    ),
    _capability(
        "CAP-010",
        "Semantic Search",
        "Intelligence",
        CapabilityPriority.P1,
        "Yes",
        "Yes",
        "Partial",
        "Medium",
        "Critical",
        "Critical",
        "MLP",
    ),
    _capability(
        "CAP-011",
        "Decision Memory",
        "Memory / Intelligence",
        CapabilityPriority.P1,
        "Yes",
        "Yes",
        "Partial",
        "Medium",
        "Critical",
        "Critical",
        "MLP",
    ),
    _capability(
        "CAP-012",
        "Tasks and Goals",
        "Memory / Operations",
        CapabilityPriority.P1,
        "Yes",
        "Yes",
        "Implemented",
        "Medium",
        "High",
        "High",
        "MLP",
    ),
    _capability(
        "CAP-013",
        "Persistent Timeline",
        "Memory / Operations",
        CapabilityPriority.P1,
        "Yes",
        "Yes",
        "Partial",
        "Medium",
        "High",
        "High",
        "MLP",
    ),
    _capability(
        "CAP-014",
        "Executive Memory Dashboard",
        "Intelligence",
        CapabilityPriority.P1,
        "Yes",
        "Yes",
        "Partial",
        "Medium",
        "High",
        "Critical",
        "MLP",
    ),
    _capability(
        "CAP-015",
        "Guided Onboarding",
        "Product Experience",
        CapabilityPriority.P1,
        "Yes",
        "Yes",
        "Planned",
        "Medium",
        "High",
        "Critical",
        "MLP",
    ),
    _capability(
        "CAP-016",
        "Knowledge Worker Interface",
        "Product Experience",
        CapabilityPriority.P1,
        "Yes",
        "Yes",
        "Partial",
        "Medium",
        "Critical",
        "Critical",
        "MLP",
    ),
    _capability(
        "CAP-017",
        "Product Navigation Shell",
        "Product Experience",
        CapabilityPriority.P1,
        "Yes",
        "Yes",
        "Planned",
        "Low",
        "Critical",
        "Critical",
        "MLP",
    ),
    _capability(
        "CAP-018",
        "Connector Health",
        "Operations",
        CapabilityPriority.P1,
        "Yes",
        "Yes",
        "Implemented",
        "High",
        "High",
        "High",
        "MLP",
    ),
    _capability(
        "CAP-019",
        "First Production Connector",
        "Integrations",
        CapabilityPriority.P1,
        "Yes",
        "Yes",
        "Partial",
        "High",
        "Critical",
        "Critical",
        "Pilot",
    ),
    _capability(
        "CAP-020",
        "Second Production Connector",
        "Integrations",
        CapabilityPriority.P2,
        "Preferred",
        "Yes",
        "Partial",
        "High",
        "High",
        "High",
        "Pilot",
    ),
    _capability(
        "CAP-021",
        "Operator Console",
        "Operations",
        CapabilityPriority.P1,
        "Yes",
        "Yes",
        "Implemented",
        "High",
        "Medium",
        "High",
        "MLP",
    ),
    _capability(
        "CAP-022",
        "Runtime Controls",
        "Operations",
        CapabilityPriority.P2,
        "Limited",
        "Limited",
        "Implemented",
        "Critical",
        "Medium",
        "Medium",
        "Pilot",
    ),
    _capability(
        "CAP-023",
        "Workspace Metrics",
        "Operations",
        CapabilityPriority.P2,
        "Yes",
        "Yes",
        "Implemented",
        "Medium",
        "Medium",
        "Medium",
        "Pilot",
    ),
    _capability(
        "CAP-024",
        "Memory Relationship View",
        "Intelligence",
        CapabilityPriority.P2,
        "Preferred",
        "Yes",
        "Partial",
        "Medium",
        "High",
        "High",
        "Pilot",
    ),
    _capability(
        "CAP-025",
        "Decision Lineage",
        "Governance / Intelligence",
        CapabilityPriority.P2,
        "Preferred",
        "Yes",
        "Partial",
        "Medium",
        "High",
        "High",
        "Pilot",
    ),
    _capability(
        "CAP-026",
        "Notifications",
        "Operations",
        CapabilityPriority.P2,
        "No",
        "Preferred",
        "Planned",
        "Medium",
        "Medium",
        "Medium",
        "Pilot",
    ),
    _capability(
        "CAP-027",
        "Persistent Event Observability",
        "Operations",
        CapabilityPriority.P2,
        "Limited",
        "Yes",
        "Partial",
        "Medium",
        "Medium",
        "High",
        "Pilot",
    ),
    _capability(
        "CAP-028",
        "Enterprise Knowledge Graph",
        "Intelligence",
        CapabilityPriority.P3,
        "No",
        "No",
        "Foundation",
        "High",
        "Critical",
        "High",
        "Post-Pilot",
    ),
    _capability(
        "CAP-029",
        "Recommendation Engine",
        "Intelligence",
        CapabilityPriority.P3,
        "No",
        "No",
        "Planned",
        "High",
        "High",
        "High",
        "Post-Pilot",
    ),
    _capability(
        "CAP-030",
        "Documentation Intelligence",
        "Knowledge Platform",
        CapabilityPriority.P3,
        "No",
        "No",
        "Foundation",
        "Medium",
        "Medium",
        "Medium",
        "Post-Pilot",
    ),
    _capability(
        "CAP-031",
        "Workflow Designer",
        "Operations",
        CapabilityPriority.P3,
        "No",
        "No",
        "Future",
        "High",
        "Medium",
        "Medium",
        "Post-Pilot",
    ),
    _capability(
        "CAP-032",
        "Advanced Analytics",
        "Intelligence",
        CapabilityPriority.P3,
        "No",
        "No",
        "Partial",
        "Medium",
        "Medium",
        "Medium",
        "Post-Pilot",
    ),
    _capability(
        "CAP-033",
        "Commercial Billing Automation",
        "Commercial",
        CapabilityPriority.P3,
        "No",
        "No",
        "Partial",
        "High",
        "Medium",
        "Medium",
        "Post-Pilot",
    ),
    _capability(
        "CAP-034",
        "Multi-Agent Orchestration",
        "Intelligence / Operations",
        CapabilityPriority.P4,
        "No",
        "No",
        "Foundation",
        "Critical",
        "High",
        "Strategic",
        "Long-Term",
    ),
    _capability(
        "CAP-035",
        "Autonomous Learning",
        "Intelligence",
        CapabilityPriority.P4,
        "No",
        "No",
        "Future",
        "Critical",
        "High",
        "Strategic",
        "Long-Term",
    ),
    _capability(
        "CAP-036",
        "Organizational Digital Twin",
        "Intelligence",
        CapabilityPriority.P4,
        "No",
        "No",
        "Future",
        "Critical",
        "High",
        "Strategic",
        "Long-Term",
    ),
    _capability(
        "CAP-037",
        "Distributed Event Broker",
        "Operations",
        CapabilityPriority.P4,
        "No",
        "No",
        "Future",
        "High",
        "Low Initially",
        "Strategic",
        "Scale Stage",
    ),
    _capability(
        "CAP-038",
        "Connector Marketplace",
        "Integrations",
        CapabilityPriority.P4,
        "No",
        "No",
        "Future",
        "High",
        "Medium",
        "Strategic",
        "Scale Stage",
    ),
)
